import React from "react";

export default function Gallery() {
  return (
    <div class="container ">
      <h1 class="bg-info text-center">GALLERY</h1>

      <img
        src={require("../assets/images/CPR1.JPG")}
        alt=""
        height="200"
        width="200"
      />
      <img
        src={require("../assets/images/CPR2.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR3.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR4.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR5.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR6.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR7.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR8.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR9.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR10.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR11.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR12.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR13.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR14.JPG")}
        alt=""
        width="200"
        height="200"
      />
      <img
        src={require("../assets/images/CPR15.JPG")}
        alt=""
        width="200"
        height="200"
      />
    </div>
  );
}
